-- CREATE TABLE IF NOT EXISTS call_logs (
--   id SERIAL PRIMARY KEY,
--   caller_id INTEGER NOT NULL REFERENCES users(id),
--   callee_id INTEGER NOT NULL REFERENCES users(id),
--   call_type TEXT NOT NULL,
--   started_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
--   ended_at TIMESTAMP WITHOUT TIME ZONE
-- );
